#!/bin/bash
#
# 2017-01-22 Nereu version using CentoS7/Mariadb
# 2017-08-08 Nereu cleaning the code

###

MYSQL_USER="root"
MYSQL_PASS=""
DBNAME="internetdb"

### 

function PAUSE {
  printf "\n  Press ENTER to continue or CTRL-C to cancel..." ; read junk
}

function ECHO {
  printf "\n%s\n\n" "$*"
}

### Main

clear 

ECHO ". internetdb"

if mysql --user="${MYSQL_USER}" --password="${MYSQL_PASS}" -e 'select 1' >/dev/null 2>&1
then
  ECHO ". MySQL avaliable"
else
  ECHO ". ERROR: Check MySQL user/password" 
  echo "  Change variables MYSQL_USER and MYSQL_PASS"
  exit 1
fi

ECHO ". This script will (re-)create and load \"$DBNAME\" database"

PAUSE

ECHO ". Backup database"

mysql --user="${MYSQL_USER}" --password="${MYSQL_PASS}" --database=${DBNAME} -e 'select 1' >/dev/null 2>&1 && \
mysqldump --user="${MYSQL_USER}" --password="${MYSQL_PASS}" --databases ${DBNAME} | \
gzip -v >${DBNAME}.sql.gz

PAUSE

ECHO ". [Re-]creating database and tables"

mysql -v -v --user="${MYSQL_USER}" --password="${MYSQL_PASS}" <<EOF

drop database if exists $DBNAME;

create database $DBNAME default charset=utf8;

use $DBNAME;

create table countries (
 id      int          not null auto_increment primary key,
 country varchar(2)   not null unique key,
 name    varchar(255) not null
);

create table networks (
  id           int         not null auto_increment primary key,
  country      varchar(2)  not null,
  network_cidr varchar(25) not null,
  network      varchar(20) not null,
  broadcast    varchar(20) not null,
  start_ip     varchar(20) not null,
  end_ip       varchar(20) not null,
  inetwork     int(10) unsigned not null,
  ibroadcast   int(10) unsigned not null,
  istart_ip    int(10) unsigned not null,
  iend_ip      int(10) unsigned not null,
  key start_end (istart_ip,iend_ip)
);

create table countries_iso31661 (
 id           int          not null auto_increment primary key,
 english_name varchar(255) not null,
 alpha2       varchar(2)   not null unique key,
 alpha3       varchar(3)   not null,
 numeric_code varchar(3)   not null
) character set utf8;

EOF

PAUSE

ECHO ". Download all-zones"

rm -f *.zone all.txt

curl 'http://www.ipdeny.com/ipblocks/data/countries/all-zones.tar.gz' >all-zones.tar.gz

tar -zxf all-zones.tar.gz \*.zone 

for f in $(ls *.zone)
do
  country=$(echo $f | sed -e 's/\.zone//')
  sed -e "s/^/${country} /" <$f
done >all.txt

PAUSE

ECHO ". Loading table [networks]..."

mysql --user="${MYSQL_USER}" --password="${MYSQL_PASS}" --database="${DBNAME}" <<EOF
load data local infile 'all.txt'
into table networks
fields terminated by ' '
( @country, @network_cidr )
set
 country      = @country                                                                                                                       ,
 network_cidr = @network_cidr                                                                                                                  ,
 network      = inet_ntoa( inet_aton(substring_index(@network_cidr,'/',1)) )                                                                   ,
 broadcast    = inet_ntoa( inet_aton(substring_index(@network_cidr,'/',1)) + ~(~((1 << (32 - substring_index(@network_cidr,'/',-1))) - 1)))    ,
 start_ip     = inet_ntoa( inet_aton(substring_index(@network_cidr,'/',1)) + 1 )                                                               ,
 end_ip       = inet_ntoa( inet_aton(substring_index(@network_cidr,'/',1)) + ~(~((1 << (32 - substring_index(@network_cidr,'/',-1))) - 1)) - 1),
 inetwork     =            inet_aton(substring_index(@network_cidr,'/',1))                                                                     ,
 ibroadcast   =            inet_aton(substring_index(@network_cidr,'/',1)) + ~(~((1 << (32 - substring_index(@network_cidr,'/',-1))) - 1))     ,
 istart_ip    =            inet_aton(substring_index(@network_cidr,'/',1)) + 1                                                                 ,
 iend_ip      =            inet_aton(substring_index(@network_cidr,'/',1)) + ~(~((1 << (32 - substring_index(@network_cidr,'/',-1))) - 1)) - 1
;

select count(*) as " Rows in networks table" from networks;
EOF

PAUSE

ECHO ". Loading tables [countries_iso31661] and [countries]..."

mysql --user="${MYSQL_USER}" --password="${MYSQL_PASS}" --database=${DBNAME}  <<EOF

# ISO 3166-1
# https://en.wikipedia.org/wiki/ISO_3166-1

set session character_set_results=utf8;

load data local infile 'iso31661.tab' 
into table countries_iso31661 
character set utf8
fields terminated by '\t'  
(@english_name,@alpha2,@alpha3,@numeric_code)
set
english_name=@english_name,
alpha2=lower(@alpha2),
alpha3=lower(@alpha3),
numeric_code=@numeric_code
;

insert into countries ( country, name ) select alpha2, english_name from countries_iso31661 order by english_name;

# Exceptions
# Ver: https://en.wikipedia.org/wiki/Country_code_top-level_domain
insert into countries (country, name) values
('ap','Asia Pacific'),
('eu','European Union'),
('uk','United Kingdom');

select count(*) as " Rows in countries table" from countries;

select * from ( select country code, count(*) n from networks group by country ) c left outer join countries i on c.code=i.country  where i.country is null;

EOF

PAUSE

ECHO ". Clean up temporary files"

rm -f *.zone all.txt

ECHO ". Finished"
